version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5416:5432  # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=ai_saas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080